### ISSUE TITLE
[Bug] Severe lag when using certain themes

### ISSUE THREAD

**Issue by mostafa-abdelbrr** [BetterDiscord/BetterDiscord#1009]
**Describe the Bug**
When using some themes like Nocturnal and OperaGX theme, BD becomes severely laggy. Some don't produce the same lag as the others, the Cyberpunk theme is less laggy but nocturnal is very laggy and OperaGX theme makes it unusable.

**To Reproduce**
Use the themes (reinstalled multiple times with no luck, tested on both Arch and Windows).

**Expected Behavior**
Severe lag when doing anything at all.

**Discord Version**
Stable.

**Comment by mostafa-abdelbrr** [comment]
I mean the themes were fine until suddenly they caused a lot of lag. I clean installed windows a couple of times while preserving the betterdiscord folder without luck. I tried disabling all plugins once but that didn't make any difference.

**Comment by rauenzi** [comment]
Lag from themes would be just that--caused by the themes themselves. Themes that use attribute selectors (i.e. `[]` style selectors), themes using wildcard and other generic selectors or many old dead selectors can all cause lag. Rendering lag can also be caused by mismanaging z layers or doing many animations/transitions without forcing a gpu render with something like `transform`.

These are not things caused by or fixable by BD itself.
