### ISSUE TITLE
[Feature] api to install chrome extensions and/or expose the Main electron process

### ISSUE THREAD

**Issue by DetachHead** [BetterDiscord/BetterDiscord#1032]
**Is your feature request related to a problem? Please describe.**
i would like to create an extension that relies on a chrome extension

**Describe the feature you'd like**
a method in `BdApi` to install a chrome extension, like `BdApi.installExtension` or something, which uses https://www.electronjs.org/docs/api/extensions

OR

expose the Main electron process, which i believe will allow for plugin developers to access this part of the electron api themselves. if this is a security concern, plugins could have an "elevated" permission that the user would have to explicitly allow if the plugin requests it

**Additional context**
i'm trying to create an extension that uses [ublock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) to block ads in the new youtube player

as far as i'm aware there's no way to intercept and block http requests from the Renderer, nor is there a way to remove elements from the youtube iframe due to the cross-origin policy

**Comment by QbDesu** [comment]
Since there is no way to access the addon buttons and because Discord uses a custom context menu in electron 99% of all extensions won't work anyway. If the ability to load plugins was added it would be part of BD itself and not a plugin api I recon. But as I said it won't work anyway. The better solution is using system-wide adblocking anyway. Either using a custom dns server, firewall or mock vpn connection that blocks such requests.

> expose the Main electron process
no, never. the processes are isolated for a reason.

**Comment by rauenzi** [comment]
Yes please see the above comment.

**Comment by NatoBoram** [comment]
> The better solution is using system-wide adblocking anyway.

Now that Discord has new integration that bypasses these (like YouTube) could you reconsider? Adding uBlock Origin, even if we don't have access to its context menu, would be absolutely worth it.

While the original suggestion was a bit misguided (like exposing the Electron process), being able to add extensions at inject-time would be awesome even if limited.
