### ISSUE TITLE
Game Overlay Keybind wont save[Bug]

### ISSUE THREAD

**Issue by GAbO1254** [BetterDiscord/BetterDiscord#1192]
**Describe the Bug**
After setting a Keybind for opening the overlay, leaving the settings page/category, it resets to "No Keybind Set"

**To Reproduce**
Set Keybind, leave page, return

**Expected Behavior**
Keybind setting being updated

**Screenshots**

**Discord Version**
Stable 112644 (2dd6bce)
BetterDiscord 1.4.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19042)

**Additional Context**
this was the same over the last few versions as well

**Comment by rauenzi** [comment]
I cannot reproduce this. Can you try disabling all your plugins, reloading, and testing again?

**Comment by GAbO1254** [comment]
Reloading automatically enabled "BDFDB" (v2.0.7), but it made no difference, it still did not update the keybind.

**Comment by SmolAlli** [comment]
If reloading causes for BDFDB to automatically turn on it's because you have other plugins enabled.

**Comment by howdoiusekeyboard** [comment]
I have faced this issue twice myself. I don't think its an issue with better discord, but with discord itself, try running your discord as administrator. If that doesn't help you would have to delete discord along with all the appdata and reinstall everything
imo this happens when installation files are corrupted
