### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SarnaxLii** [BetterDiscord/BetterDiscord#1219]
When creating the invite server link, immediately encountered an ERROR issue.

![image](https://user-images.githubusercontent.com/94861415/154198353-593387b9-f65c-43ef-bed0-003b6bdbd879.png)

**Comment by FlexGamesGitHub** [comment]
Could you check the console for an error and add it to this pls? (guess it's because of a construction error in ZeresPluginLib and some warnings from BDFDB and thus plugins failing to do their stuff)
(just finding this interesting though I guess it'll be fixed soon and also this bug report is not after the template rules so probably gonna be closed soon)

**Comment by rauenzi** [comment]
Please try this without any plugins and use the correct issue template to provide needed information
