### ISSUE TITLE
[Bug] Using directional keys in guild list

### ISSUE THREAD

**Issue by yorik100** [BetterDiscord/BetterDiscord#1223]
**Describe the Bug**
Up and down arrow keys don't work when clicking inside the Discord guild list

**To Reproduce**
Click next to a guild list, press right then down/up arrow key to navigate through the guild list, it will not do anything past 1.4.0 BD version

**Expected Behavior**
https://i.gyazo.com/5546d74c191c3dcff2fdfa84c63be809.gif

**Screenshots**
https://i.gyazo.com/5546d74c191c3dcff2fdfa84c63be809.gif

**Discord Version**
Stable

**Additional Context**
Worked in 1.4.0 and works on browser version

**Comment by MGPlayzYT** [comment]
Experiencing the same issue. It's annoying since I'm using a touchpad with no scroll gestures.

**Comment by Simon818** [comment]
There are screen-reader users who now can't use Discord with BetterDiscord installed because of this bug. I wanted to recommend it because it provides workarounds for some other issues we've been experiencing, but can't do that until we figure this out.

Commented in my own issue that turned out to be a duplicate, but re-commenting here so all the information is in one place.

**Comment by rauenzi** [comment]
Can you please reach out on Discord to test a version that may fix this?

**Comment by Simon818** [comment]
I've been on vacation but haven't forgotten about this, and am very interested in testing. Where should I reach out? My Discord is SLJ#0001 if that's easiest. I'm also in the BetterDiscord server. I'll be around starting early next week.

**Comment by rauenzi** [comment]
This has the same root issue as #1203
