### ISSUE TITLE
[Bug] BetterDiscord doesn't inject properly, crashes when going to server settings

### ISSUE THREAD

**Issue by subby2006** [BetterDiscord/BetterDiscord#1226]
**Describe the Bug**

BetterDiscord doesn't load and no plugins are loaded. The mod also causes discord to crash when going into server settings
**To Reproduce**

Open Discord, BetterDiscord loading icon and plugin loaded messages are absent, as well as options in user settings menu. Discord also crashes when you open server settings
**Expected Behavior**

BetterDiscord should load with the icon and plugin loaded messages should appear
**Screenshots**

https://user-images.githubusercontent.com/65925208/154416597-46c22da5-6e79-4cc7-8cea-b4926c637c8f.mp4
**Discord Version**

Stable 115205 (40ca1c6) Host 1.0.9003 Windows 10 64-Bit (10.0.19043)
**Additional Context**

**Comment by SmolAlli** [comment]
1. If you do not have the BetterDiscord settings, then please try to reinstall. If this persists, then please [Join the Discord server](https://betterdiscord.app/invite) where someone will help you get the correct path to install BetterDiscord into.
2. The crashes that occur from performing certain actions have not been conclusively shown to be caused by BetterDiscord itself. Please check that none of your plugins are causing this crash, and if it occurs on Vanilla discord, then there is essentially no reason to believe that BetterDiscord is the cause.

**Comment by Arctrometa** [comment]
I've got the exact same issue, perhaps this could be another side effect of the newer discord updates?

**Comment by subby2006** [comment]
After downloading the installer and using the repair, betterdiscord now seems to be working well. Closing my issue
