### ISSUE TITLE
Why dont you try making a web app for this? (feature)

### ISSUE THREAD

**Issue by Eggyboi156** [BetterDiscord/BetterDiscord#1245]
Basically its like the discord web app but its betterdiscord instead! :)

**Comment by SmolAlli** [comment]
There was one at one point that was created by one of the contributors for BD, but AFAIK he has not been giving it full updates.
The main reasons that it existed was due to there being token loggers and other not-so-fun things on the ones that exist on the Chrome store, and that a lot of people do request this.
The main reasons that it isn't kept up is because it is a lot of work to try and make everything work with the browser version of Discord (mainly with stuff like people not fully understanding how to upload their addons, and some addons not working with the Web version of BetterDiscord), and it costs money to put it on the Chrome store, which is not something that the original developer (of the most official version of it) was not willing to do.
So if someone does end up making a new version of BD for the browser version of Discord, it'll most likely be at least slightly separated from the main BD.
So, I guess the reason is because it's a whole lot more work on top of the BetterDiscord that already exists, and because BetterDiscord was mainly designed for the desktop version of Discord.

**Comment by QbDesu** [comment]
If you want a client mod that runs in the web browser I'd recommend using GooseMod. A lot of BD's features are based on electron APIs and a lot of BD plugins are highly based around file system access and direct access to node/electron apis which BDBrowser tried to emulate but it was mostly based on compatibility hacks for a system and plugins that were never intended for the browser.

**Comment by sapioit** [comment]
The problem with the store could be solved by making it into an userscript, using existing extensions like TamperMonkey, ViolentMonkey, and so on.

**Comment by rauenzi** [comment]
No thanks!
