### ISSUE TITLE
[Feature] Disable the annoying crash pop up that blocks better discord plugins

### ISSUE THREAD

**Issue by GithubPremiumPlan** [BetterDiscord/BetterDiscord#1291]
**Disable Crash Pop-up**
Please add the option to disable that annoying pop up that disables plugins and themes, you REFUSE to patch your own memory leaks so why force the plugins off when its your own plugins that cause it.

**Additional context**
I really do not care that it crashes from too much memory, just make it so it reloads everything right away to clear memory instead of killing the plugins or you know, fix your memory leaks.

**Comment by ItMeSarah** [comment]
The vast majority of the time, it is not crashing due to a memory leak, it's crashing because you have a plugin that is broken due to Discord changing a module that said plugin relies on.   And if it is crashing due to a memory leak, then you have a plugin that needs to coded better to not have said memory leak, which all of the ones on the site are checked to not have memory leaks and or malicious additions that would cause issues. So it's not BetterDiscord at fault, and nothing about BetterDiscord needs to be changed.

**Comment by GithubPremiumPlan** [comment]
The crashing is not instant, it crashes after memory gets too high, all of DevilBro's plugins leak memory and once it goes past 2000 it reloads itself to clear the memory, using a memory cleaner helps prevent crashes and makes betterdiscord run smoother, DB will deny any memory leak and say he will not fix it because it doesn't exist but there are tons of people who say otherwise.

I really do not care that it leaks but the forced disabling plugins from a memory crash that i did not consent to is annoying, something should always have a toggle.

**Comment by Tropix126** [comment]
> The crashing is not instant, it crashes after memory gets too high.

Memory leaks are not the only cause of a renderer crash. As mentioned earlier, the vast majority of the time it's due to plugins causing an immediate crash on load. The popup is there to prevent discord from crash-looping in that event.

Renderer process crashes are caused by low-level v8 internals being unable to reconcile with a plugin throwing certain errors, and thus have no stacktrace or method of identifying what specifically caused a crash, so we can't exactly tell the difference between a plugin leaking memory and some flaky node error that immediately throws.

It's not the BD client's responsibility to patch plugin memory leaks, so this is probably better reported to devilbro.

**Comment by GithubPremiumPlan** [comment]
DB has time and time again refused to acknowledge the memory leaks and even deny they exist, he will not fix it.

**Comment by notmike101** [comment]
> DB has time and time again refused to acknowledge the memory leaks and even deny they exist, he will not fix it.

The alternative there is to just make the plugin yourself.

**Comment by rauenzi** [comment]
Going to dup forward to a less aggressively title issue #1304
