### ISSUE TITLE
Can't start discord (stuck in loading with BD logo in the right bottom corner)[Bug]

### ISSUE THREAD

**Issue by Pxx500** [BetterDiscord/BetterDiscord#1337]
**Describe the Bug**

Can't start discord
**To Reproduce**

Doesn't seem to affect anyone else since there would be many issues with this problem
**Expected Behavior**

Discord loading properly
**Screenshots**

![image](https://user-images.githubusercontent.com/81298696/179310414-82e12cd9-6d72-4870-b185-ac7287e77cfb.png)
**Discord Version**

Stable
**Additional Context**

I don't see any logs, where can I find them?

**Comment by SmolAlli** [comment]
> I don't see any logs, where can I find them?
Logs can be enabled in BetterDiscord's settings, but since it is not loading, you may have luck doing the following:
1. press `win r` and pasting in `notepad.exe %appdata%\BetterDiscord\data\stable\settings.json` to open up the settings file.
2. changing the below from "before" to "after":
```
// Before:
"developer": {
        "debugLogs": false,

// After:
"developer": {
        "debugLogs": true,
```
and restarting Discord and `ctrl r`. This should add some debugging logs to the BetterDiscord folder.
Please join the [Discord server](https://betterdiscord.app/invite) for more help, as you will be answered more easily, and generally faster.

**Comment by Pxx500** [comment]
I managed to fix it and It seems to have been caused by discord itself and not BD but I'm not sure why.
I disabled cache in networking tab and it helped so I think this issue can be closed because it's not connected to BD.

**Comment by iDefineHD** [comment]
if Anyone has this, Do the steps below.

Steps:
1. Go to "run" (Window key + R)
2. Type "%appdata%" and hit enter
3. Delete the "Discord" folder or the "Cache" folder inside Discord folder
4. Launch the Discord app
