### ISSUE TITLE
[Feature] Trust this domain - Trust all domains...

### ISSUE THREAD

**Issue by smashedr** [BetterDiscord/BetterDiscord#1398]
When you click on a link in discord, it gives you a popup saying "HOLD UP" and you have to click "Trust this Domain" for every domain in the world.

Possible to add a feature to automatically trust all domains so I never have to click the "Trust this Domain" button and can open links like a normal human?

**Comment by rauenzi** [comment]
I don't intend to add this to BD, no

**Comment by Saiapatsu** [comment]
@smashedr
For what it's worth, this dialog rarely bothers me because I middle-click all images and links, which universally means 'open this link in the background and continue'.  This does not show any dialog.  
Left-clicking external links in Discord does not make sense because the Discord app will not navigate away from Discord.  
So I suggest middle-clicking links.
