### ISSUE TITLE
[Bug] Discord Crashes when attempting to open themes menu or plugins menu

### ISSUE THREAD

**Issue by secretknowledge** [BetterDiscord/BetterDiscord#1578]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I noticed this issue today when opening discord. I clicked on the themes menu and discord crashed and gave me the "Well this is awkward" screen. It did not seem to be fixed after fresh install of both BetterDiscord and Discord. Can you help? It was working yesterday.

### Expected Behavior

I expected to open the themes menu and be able to change themes.

### Steps To Reproduce

(Windows)
Install discord + betterdiscord
Open themes
Crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

**Comment by Michael-Stokoe** [comment]
![image](https://user-images.githubusercontent.com/2981213/227007973-e27537e3-7d45-4951-b3c9-89fc849e149a.png)

**Comment by maenDisease** [comment]
See https://github.com/BetterDiscord/BetterDiscord/commit/6e4d309e49953ed5be0a04c37ea9810b949073f2

**Comment by SimpleCppCoder** [comment]
> See [6e4d309](https://github.com/BetterDiscord/BetterDiscord/commit/6e4d309e49953ed5be0a04c37ea9810b949073f2)

I see that commit was merged into main, when can we expect the BetterDiscord patch to show up in the updater?

Otherwise replacing `"C:\Users\%UserProfile%\AppData\Roaming\BetterDiscord\data\betterdiscord.asar"` with the build artefact found [here](https://github.com/BetterDiscord/BetterDiscord/actions/runs/4493512010) fixes the problem!
