### ISSUE TITLE
[Feature] Enabling Wayland over on Linux

### ISSUE THREAD

**Issue by Tarballwalf** [BetterDiscord/BetterDiscord#1595]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

A toggle in the BD settings to enable Wayland over on Linux, this could be done by adding the `--enable-features=UseOzonePlatform` and `--ozone-platform=wayland` flags to the Discord client. 
From my testing, along with Discord's embedded Electron now bumped to version 22, It's stable enough to be used.

**Comment by QbDesu** [comment]
There is currently no reasonable way of doing this. BD loads after Discord was already started, so in order to set such parameters we would have to trigger a relaunch of the application.
On top of this if somebody were to enable this option on a non-Wayland environment, Discord would no longer open at all, so the option would have to be turned off by modifying a settings file. So we'd have to implement it with added complexity to safe-guard against this.

Wayland support is also still an experimental electron feature, even if it's relatively stable in day-to-day use. But really the step of automatically selecting the appropriate render platform is something that should be implemented on chromium's end once it's a stable feature in their books.

The much simpler way which you'll have to resort to for the time being is adjusting the DesktopFile entry and adding these flags yourself in the Exec line there. Plasma and Gnome have graphical settings dialogs for this, for sway or alike you'll have to modify it somewhere in `/usr/share/applications` either directly in place or by copying it to `~/.local/share/applications` and modifying it there. For more details on this [refer to the Arch wiki](https://wiki.archlinux.org/title/Desktop_entries#Modify_desktop_files)

**Comment by rauenzi** [comment]
@QbDesu Would using the command line api in electron be insufficient to apply these options?

**Comment by rauenzi** [comment]
Going to close this as out of scope.
