### ISSUE TITLE
[Feature] Turn off BD disabling on crash

### ISSUE THREAD

**Issue by jlaine3333** [BetterDiscord/BetterDiscord#1667]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

BD disables itself every time Discord crashes. While this is usually a good feature to prevent not being able to use Discord due to a crash loop from a plugin, it also means debugging a Discord-related crash (which has nothing to do with BD) is twice as annoying, because I want to keep BD enabled and have to hit the Try Again button every single time. I would like an option to turn off BD's disabling feature, and for obvious reasons it can have a big warning sign next to it telling people not to turn it on unless they know what they're doing.

**Comment by Riddim-GLiTCH** [comment]
This will likely never happened. This feature was implemented to protect discord from bootlooping as you have said. It allows the user to remova a faulty plugin before restarting discord. 

I am also fairly certain that the type of crash you speak of is specifically tied to a BD addon malfunctioning, And if this type of crash occurs often, one can turn on debug logging in BD's settings to save crash dumps to a file

I would also like to add that its honestly not worth adding a toggle for this, as it takes less than a second to click the retry button.

**Comment by froyo4u** [comment]
> I would also like to add that its honestly not worth adding a toggle for this, as it takes less than a second to click the retry button.

yeah sure it takes less than a second to click the try again button, but the problem is that I then have to wait longer for my discord to load as it has to restart a total of two times after a crash. They aren't the only one who are requesting a feature like this. I just haven't found the time to put in a feature request here. And looking at the code that handles the crash detection, it really doesn't seem like it would be too difficult to implement.

If I were to implement this myself and create a pull request, would you accept this feature addition that way?

**Comment by LoganDark** [comment]
this constantly annoys me because of my broken GPU. multiple times a day I will try to tab into Discord just to find out that it has "helpfully" disabled BD because it thinks that it has crashed. then I have to find the dialog and get it to restart *again*, and if I'm lucky then I might remember what I was actually intending to do. this feature does not help me in any way and has been absolutely nothing but a useless annoyance at best
