### ISSUE TITLE
[Feature] Option to turn off crash detection

### ISSUE THREAD

**Issue by LoganDark** [BetterDiscord/BetterDiscord#1703]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

my GPU recently broke, so Discord will crash randomly and BD will disable itself, even though it really doesn't need to. I would appreciate an option to turn off this detection, because having to restart Discord manually after it has already crashed is really annoying

**Comment by Riddim-GLiTCH** [comment]
Please see #1667

**Comment by LoganDark** [comment]
oops. I thought I remembered something like that but couldn't find it. For the record I do hate this culture of trying to protect the user from themself & not allow them to turn it off. There exist people who don't need or want the help, like in this case.

**Comment by Riddim-GLiTCH** [comment]
Sadly that is a requirement with the average user having an IQ of 5.

I'm not saying this is the best solution either, but if they were to implement this, users would likely enable it, forget about it and then come crying to the support server because their discord is broken and they do not know what could be wrong.

As Zerebos said:
> Yeah I won't even consider something like this until we improve crash detection and error recovery, sorry.

Maybe at some point in the future this will be added, but for now, both the error handling and the users can not be trusted entirely.

**Comment by LoganDark** [comment]
> Sadly that is a requirement with the average user having an IQ of 5.

it is *not* a requirement for this to have absolutely no mechanism for disablement. it doesn't have to be an easy toggle, but if I have to fork the entirety of BetterDiscord just to get it to behave properly, I'm going to be a little annoyed.
