### ISSUE TITLE
[Feature] Auto detection of flatpak discord

### ISSUE THREAD

**Issue by mak448a** [BetterDiscord/BetterDiscord#1717]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Could you auto detect the flatpak version of Discord, just like the normal version? It installs fine when manually selecting the directory `~/.var/app/com.discordapp.Discord/config/discord/0.0.x`

### Anything else?

![image](https://github.com/BetterDiscord/BetterDiscord/assets/94062293/7608b3e1-8aa8-4a77-82a6-e755676ded03)

**Comment by Riddim-GLiTCH** [comment]
Flatpak is not supported.

**Comment by mak448a** [comment]
But it worked when I installed it, so....

**Comment by Riddim-GLiTCH** [comment]
Just because its not supported, doesn't mean it wont work. There's always a workaround.

From my understanding, only standard local installs are officially supported. This means that the installer expects the discord package to be located in a specific path, one that if I understand correctly is the same across all flavors of Linux, Assuming you install the official discord package with the official distro-specific package manager.

From my understanding, the Flatpak version is a repack of the discord app, designed to run in a sandbox. Thus, it is not the standard package that the installer expects.
I'm not saying I don't appreciate the added privacy and security this boasts. But I honestly feel like if you're really that paranoid about privacy, you shouldn't really use discord in the first place, as it still stores the data from your activity on the actual platform. Besides, application tracking and such can already be mitigated with the standard install, and [the DoNotTrack plugin](https://betterdiscord.app/plugin/DoNotTrack). Rendering the point of using betterdiscord on flatpak to basically none.

**Comment by mak448a** [comment]
Just using the flatpak to have updates without having to reinstall the tar.gz. file. Anyway, I can close the issue if you want. Thanks for the information.

**Comment by SmolAlli** [comment]
For flatpak and snap versions, it is recommended to use the [betterdiscordctl](https://github.com/bb010g/betterdiscordctl) tool rather than the official installer, as it is created more to accommodate those.

**Comment by mak448a** [comment]
Sorry, I'll open it there

**Comment by Ao1Pointblank** [comment]
> I'm not saying I don't appreciate the added privacy and security this boasts. But I honestly feel like if you're really that paranoid about privacy, you shouldn't really use discord in the first place, as it still stores the data from your activity on the actual platform.

People don't just use Flatpak for privacy. They are also very easy to install, require no password to update, and are widely accepted as the new norm. Completely ignoring Flatpak is pretty silly in the long term, and will really just result in people using the old and perhaps eventually outdated CLI betterdiscordctl project.
I am baffled as to why Flatpak is still not supported "officially".

**Comment by Riddim-GLiTCH** [comment]
> > I'm not saying I don't appreciate the added privacy and security this boasts. But I honestly feel like if you're really that paranoid about privacy, you shouldn't really use discord in the first place, as it still stores the data from your activity on the actual platform.
> 
> People don't just use Flatpak for privacy. They are also very easy to install, require no password to update, and are widely accepted as the new norm. Completely ignoring Flatpak is pretty silly in the long term, and will really just result in people using the old and perhaps eventually outdated CLI betterdiscordctl project. I am baffled as to why Flatpak is still not supported "officially".

I do not wanna turn this thread into a discussion about how to use linux. So I will say this, then leave it alone. But I disagree with this whole unification thing personally, as Linux is supposed to be flexible and extremely customizable. I do not like the idea of unifying the experience across the board as it removes space for flexibility and customizability. Rather, it promotes hardening.  I fear that Linux will lose its ability to be truly unique per user. Which is why I stand against flatpak.
