### ISSUE TITLE
[Bug] "Display Current Activity As Status Message" setting resets after opening app every time

### ISSUE THREAD

**Issue by garshmo** [BetterDiscord/BetterDiscord#1721]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

The setting for "Display Current Activity As Status Message" keeps resetting to off after every time discord is launched

### Expected Behavior

it should remember the setting choice, if you turn it on, it reverts back to off next time you launch discord

### Steps To Reproduce

1. turn Display Current Activity As Status Message to on
2. restart betterdiscord
3. it's now set to off again

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.7

**Comment by ItMeSarah** [comment]
Unable to reproduce, seems more likely your Discord is corrupted and settings aren't being saved in the settings file. Usually due to multiple version folders or multiple discord installation folders. Follow this https://support.discord.com/hc/en-us/articles/115004307527 and also if %programdata%/discord exists, delete that one as well.

**Comment by Riddim-GLiTCH** [comment]
I also wonder if they maybe checked the box for it not being caused by an addon too hastily. DoNotTrack by Zerebos also disables RPC server on start.

**Comment by garshmo** [comment]
> I also wonder if they maybe checked the box for it not being caused by an addon too hastily. DoNotTrack by Zerebos also disables RPC server on start.

wow thank you this was the problem, it was DoNotTrack, thank you for the help
