### ISSUE TITLE
[Bug] BetterDiscord and Vencord both installed do not work

### ISSUE THREAD

**Issue by Legends-of-NGDB** [BetterDiscord/BetterDiscord#1741]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I think this is because Vencord is trying to get rid of their competition. Come on guys! Strike back!

### Expected Behavior

It installs BetterDiscord and Vencord and I have access to both.

### Steps To Reproduce

Install Vencord
Install BetterDiscord
Open Discord
Go to Settings
Only Vencord is there

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

idk latest

### Anything else?

no

**Comment by shamshitty** [comment]
you cant have two client mods installed at the same time, client mods generally arent designed to work with others since theyll conflict
also theres no "competition", people use what they want to use depending on their needs. if you really want both just install canary or ptb and install the other client mod you want into that

**Comment by Riddim-GLiTCH** [comment]
This is probably the single most hilarious issue I've read so far. I wonder if they posted the same for BetterDiscord on the Vencord forums.

**Comment by sang765** [comment]
Hello, it seems like you're like me 2 months ago when I tried to install both BD and VC at the same time into Discord when I tried to imagine the scenario of having settings menus for both clients and then foolishly accepted it. It turns out that Vencord's settings override BD's settings, but when Discord crashes, BetterDiscord's crash popup will still appear even if you are using the Vencord client.

**Comment by Legends-of-NGDB** [comment]
> you cant have two client mods installed at the same time, client mods generally arent designed to work with others since theyll conflict also theres no "competition", people use what they want to use depending on their needs. if you really want both just install canary or ptb and install the other client mod you want into that

I tried Canary, however, Vencord is still dominant.

**Comment by shamshitty** [comment]
i probably worded it badly but i meant that you could try installing one of the mods on each client, so say bd on stable and vencord on canary
anyway this issue shouldnt stay open any longer since it isnt actually a bug

**Comment by Riddim-GLiTCH** [comment]
If you ask me,
> Come on guys! Strike back!
This alone deservew to be immortalized given the context lmao

But yea, this thread had no reason to exist in the first place. (You could have just asked about it in the support server and this would have been resolved pretty much the same day) And I'm pretty sure V doesn't even like the idea of competing with BD.
