### ISSUE TITLE
[Feature] Preintegrate the most important plugin libarys

### ISSUE THREAD

**Issue by siltentassasin** [BetterDiscord/BetterDiscord#757]
Is it possible to pre integrate the most used plugin libarys?

like:

BDFDB and ZeresPluginLibrary

**Comment by Tropix126** [comment]
Doing this would have siginificant performance consequences on the BD core, as many of those libraries are both large and would have duplicate functions. Added to that, BDFDB in particular is highly volatile because it acts as DevilBros personal library, and gets many breaking changes per day. These would be both difficult to document and have performance effects on BD.

There are some talks to add some common zlib functions into BD's core, but this would be by no means a full library.

**Comment by rauenzi** [comment]
Many of the developers agreed that the additional bloat from my library (ZeresPluginLibrary) would be a worthwhile addition to BD. It is something I would like to do (and revamp the plugin api in general) but it has been lower priority lately with everything going on.
