### ISSUE TITLE
[Bug] "Disable Media Keys" option does not work in 0.0.15

### ISSUE THREAD

**Issue by HanabishiRecca** [BetterDiscord/BetterDiscord#854]
"Disable Media Keys" option does not work in 0.0.15. Worked fine earlier.

Discord 0.0.15 Stable 88979
BetterDiscord 1.1.1

Related to #410

**Comment by JesseStorms** [comment]
I can still confirm this is still an issue.

`-disable-features=HardwareMediaKeyHandling,MediaSessionService` doesn't get set in any Discord process when looking at the Command Line field in Task Manager/[Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).

If I'd had to make a guess, it's that [line 123 on ./injector/src/modules/betterdiscord.js](https://github.com/BetterDiscord/BetterDiscord/blame/main/injector/src/modules/betterdiscord.js#L123) doesn't get run. Judging by commit https://github.com/BetterDiscord/BetterDiscord/commit/826aa7999cd941c775e47d21176d284696f47915, it might've been an issue since v1.1.0, but Discord might've done something stupid that broke it. 

I've looked at both on Discord Stable 111330 and Discord Canary while using BetterDiscord 1.3.0 and both showed the same issue. On Canary it actively takes your play/pause hostage, but I suspect that's on Discord rather then on BD.

I'd attempt to fix it myself and make a pull request, but I have no clue what I'm doing here, but I think this might be valuable information to have.

**Comment by rauenzi** [comment]
I have been testing, this line is definitely run, but it gets overridden by Discord. It seems electron does not combine args when called twice so it replaces instead. This should be fixed in the next update
